### ISSUE TITLE
Need to set destination IP ("dst" attribute) in event payloads

### ISSUE THREAD

**Issue by hermansb** [IBM/node-log4js-qradar-syslog-appender#10]
<from an email>
Team, we have problem with QRadar event processing, that needs to be addressed by augmenting event payloads.

In looking at offenses, I noticed several offenses like the one in the screen shot at the bottom of this note, which involved many events from different applications. As you can see, the offense was for "Login Failures Followed By Success to the same Destination IP preceded by Multiple Login failures to the same Destination". Qradar was confused by the fact that all of these events had the same destination (application) IP even though they were from different applications. This is because if the source & destination IPs are not set in the event payload, then QRadar determines them from the packets. Since all packets for all applications come from syslog-ng, they all have the same src and dst IP addresses.

The solution to this problem is to set the "dst" attribute in payloads. I tested this and it seems to work. The destination IP would be the IP address of the system on which your application is running. If it's possible to determine that from application code, that would be best. If that's absolutely impossible for some reason, we can probably generate an artificial IP from a hash of the application name, or something like that. However, I think that there should be a way to obtain the IP. Perhaps this can be done in middleware being used to generate the events.

In any case, we need to set some unique value for "dst" attribute in all application events. Do you see any problem in adding this?

Without this disambiguation, it will be much more difficult for application teams to monitor their offenses. These types of false positives will be generated, and teams will have to filter the list of associated events to determine if their application events were the ones with a probelm.

I do see that some events have set dst (as well as src) and that is being reflected in the events. For example:
<131>Nov 18 13:18:59 devops.ng.bluemix.net otc-orion-server-yp[10157]: "event":"Web Service Login Succeeded" "usrName":"peetersb@schneider.com" "res":"/devops/code/task/temp/<id>" "oper":"DELETE" "src":"169.55.5.108" "srcPort":"9443" "dst":"169.55.14.77" "dstPort":"9443"

**Comment by hermansb** [comment]
We should be able to do this using `os.networkInterfaces()` (we did this before in either this or the logmet appender - need to dig through history to see what we did perhaps).

**Comment by simonkotwicz** [comment]
this should probably be done in the node-qradar-audit-logs-middleware

**Comment by hermansb** [comment]
Fixed in the middleware (as seen above)
